### ISSUE TITLE
Always updates

### ISSUE THREAD

**Issue by rugk** [SeanJM/atom-css-clean#31]
This package is marked as having an update and when updated it still has an update.

**Comment by SeanJM** [comment]
That is not good. I'll push another update, we'll see if that fixes it.

**Comment by SeanJM** [comment]
Fixed?

**Comment by ricklecoat** [comment]
Seems to have done the trick, thanks.

**Comment by soderlind** [comment]
I'm still getting this:

```bash
~/Sites/dev/app/public » apm outdated
Package Updates Available (1)
└── css-clean 2.19.0 -> 2.19.6
```

**Comment by SeanJM** [comment]
Can you code? I gotta be honest, with clients and work right now--I could use some help. :)

**Comment by soderlind** [comment]
The fix was simple, I had `css-clean` and since you've renamed it I:

```bash
apm remove css-clean
apm install atom-css-clean
```

**Comment by SeanJM** [comment]
That is a bummer/easy fix. I tried to resolve that with someone from the Atom team. Thank you for posting your solution!
