### ISSUE TITLE
Css-grid is deleted

### ISSUE THREAD

**Issue by SkelegonDK** [SeanJM/atom-css-clean#36]
Hi Sean, Css-clean is deleting all my css-grid code whenever I use it!
it makes this
`.site {
  padding:10px;
  box-sizing: border-box;
  height: 100vh;
  display: grid;
  grid-template-columns: 2fr 1fr 1fr 1f;
  grid-template-rows: 1fr 1f 3fr 1fr;
  grid-column-gap:10px;
  grid-row-gap: 10px;
  grid-template-areas:
    "nav nav nav nav"
    "header header side side"
    "main main side side"
    "main main footer footer";
}`
into
`.site {
  display    : grid;
  box-sizing : border-box;
  height     : 100vh;
  padding    : 10px;
}`
Thanks for css-clean! I'm always using it now!

**Comment by awside** [comment]
Same issue, please fix this, css-clean is awesome.

**Comment by SeanJM** [comment]
Updated
